package com.Discord.DiscordBot.Z_Units;

import com.Discord.DiscordBot.Units.Question;

import static com.Discord.DiscordBot.Units.QuestionBank.unit8Questions;

public class Unit8 {

    public static int numUnit8Questions;

    public static void initializeUnit8Questions() {

        unit8Questions.add(new Question(
                "Find the area between y = x^2 and y = x.",
                "1/6", "1/2", "1/3", "1/4",
                "C", 8, 7000, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of a solid obtained by rotating y = x^2 from x=0 to x=1 around the x-axis.",
                "π/5", "π/2", "π/3", "π/4",
                "A", 8, 7001, "medium"));

        unit8Questions.add(new Question(
                "Find the average value of f(x) = x^3 on [0,2].",
                "2", "4", "3", "1",
                "A", 8, 7002, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of a solid generated by rotating y = sqrt(x) about the x-axis from x=0 to x=4.",
                "32π/3", "8π/3", "16π/3", "4π/3",
                "A", 8, 7003, "hard"));

        unit8Questions.add(new Question(
                "Find the area between y = sin(x) and y = cos(x) on [0, π/4].",
                "√2/2 - 1/2", "1/2", "1/√2", "π/4",
                "A", 8, 7004, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 3t^2. Find the displacement from t = 0 to t = 2.",
                "8", "4", "12", "6",
                "A", 8, 7005, "easy"));

        unit8Questions.add(new Question(
                "Find the area between y = e^x and y = 1 on [0,1].",
                "e - 2", "e - 1", "1 - e", "2 - e",
                "A", 8, 7006, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of a solid obtained by rotating y = x around the y-axis from y=0 to y=2.",
                "8π/3", "4π", "2π", "2π/3",
                "A", 8, 7007, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = t^2 - 2t. Find the displacement from t=0 to t=3.",
                "0", "-1", "1", "2",
                "B", 8, 7008, "medium"));

        unit8Questions.add(new Question(
                "Find the work done by a force F(x) = x^2 from x=0 to x=3.",
                "9", "27", "18", "36",
                "B", 8, 7009, "medium"));

        unit8Questions.add(new Question(
                "Compute the area between y = x^3 and y = x on [0,1].",
                "1/4", "1/2", "1/3", "1/6",
                "C", 8, 7010, "medium"));

        unit8Questions.add(new Question(
                "Find the centroid of the region bounded by y = x^2 and y = 0 on [0,1].",
                "2/3", "3/4", "1/2", "1/3",
                "C", 8, 7011, "hard"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = x^3 from x=0 to x=2 around the x-axis.",
                "16π/5", "8π/5", "32π/5", "4π/5",
                "A", 8, 7012, "hard"));

        unit8Questions.add(new Question(
                "Find the area under y = ln(x) from x=1 to x=e.",
                "1", "0", "e", "2",
                "A", 8, 7013, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 4 - t^2. Find the total distance traveled from t=0 to t=2.",
                "16/3", "8/3", "4", "12/3",
                "A", 8, 7014, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of a solid obtained by rotating y = sqrt(4 - x^2) about the x-axis from x=0 to x=2.",
                "4π", "2π", "π", "8π",
                "A", 8, 7015, "hard"));

        unit8Questions.add(new Question(
                "Find the area between y = x and y = x^2 on [0,1].",
                "1/6", "1/2", "1/3", "1/4",
                "A", 8, 7016, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 5t. Find the displacement from t=0 to t=2.",
                "10", "5", "4", "8",
                "A", 8, 7017, "easy"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = x^2 from x=0 to x=1 about the y-axis.",
                "π/2", "π/3", "π/4", "π/5",
                "A", 8, 7018, "medium"));

        unit8Questions.add(new Question(
                "Find the area under y = 1/x from x=1 to x=e.",
                "1", "e", "ln(e)", "0",
                "A", 8, 7019, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of a solid obtained by rotating y = x + 1 about the x-axis from x=0 to x=2.",
                "14π/3", "10π/3", "8π/3", "12π/3",
                "A", 8, 7020, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = e^x and y = x + 1 on [0,1].",
                "e - 1/2", "e - 1", "e - 3/2", "1/2",
                "A", 8, 7021, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = t^2 - 4t + 3. Find the displacement from t=0 to t=3.",
                "0", "1/2", "3", "2",
                "A", 8, 7022, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = x^2 + 1 from x=0 to x=1 about the x-axis.",
                "8π/3", "4π/3", "5π/3", "6π/3",
                "C", 8, 7023, "medium"));

        unit8Questions.add(new Question(
                "Find the average value of f(x) = sqrt(x) on [0,4].",
                "4/3", "2", "8/3", "1",
                "A", 8, 7024, "medium"));

        unit8Questions.add(new Question(
                "Compute the work done by F(x) = x^3 from x=0 to x=2.",
                "4", "2", "8", "16",
                "C", 8, 7025, "medium"));

        unit8Questions.add(new Question(
                "Find the area under y = cos(x) from x=0 to x=π/3.",
                "1/2", "1/4", "√3/2", "√3/4",
                "D", 8, 7026, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = 1 - x^2 from x=0 to x=1 about the x-axis.",
                "π/2", "2π/3", "π/3", "π/4",
                "A", 8, 7027, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 3t^2 - 6t. Find the total distance traveled from t=0 to t=3.",
                "9", "6", "12", "15",
                "A", 8, 7028, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = x^2 + x and y = 2x on [0,1].",
                "1/6", "1/3", "1/2", "1/4",
                "B", 8, 7029, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = sqrt(x) from x=0 to x=4 about the y-axis.",
                "64π/3", "32π/3", "16π/3", "8π/3",
                "B", 8, 7030, "hard"));

        unit8Questions.add(new Question(
                "Find the centroid of the region under y = x^2 on [0,1].",
                "3/4", "1/2", "2/3", "1/3",
                "D", 8, 7031, "hard"));

        unit8Questions.add(new Question(
                "Compute the area between y = ln(x) and y = x - 1 on [1,e].",
                "e - 2", "1", "e - 1", "2",
                "A", 8, 7032, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 2t + 1. Find the displacement from t=0 to t=3.",
                "12", "9", "6", "15",
                "B", 8, 7033, "easy"));

        unit8Questions.add(new Question(
                "Compute the volume of a solid obtained by rotating y = e^x from x=0 to x=1 about the x-axis.",
                "π(e^2 - 1)", "π(e - 1)^2", "π(e^2 + 1)", "π(e - 1)",
                "A", 8, 7034, "hard"));

        unit8Questions.add(new Question(
                "Find the area under y = 1/(x+1) from x=0 to x=1.",
                "ln(2)", "1/2", "1", "2",
                "A", 8, 7035, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = x^3 from x=0 to x=1 about the y-axis.",
                "π/2", "π/4", "π/3", "π/5",
                "B", 8, 7036, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = x^2 and y = x on [0,1].",
                "1/6", "1/2", "1/3", "1/4",
                "A", 8, 7037, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 4 - t^2. Find the total distance traveled from t=0 to t=2.",
                "16/3", "8/3", "4", "12/3",
                "A", 8, 7038, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of a solid obtained by rotating y = x^2 + 1 about the x-axis from x=0 to x=1.",
                "8π/3", "4π/3", "5π/3", "6π/3",
                "C", 8, 7039, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = x^2 and y = x^3 on [0,1].",
                "1/12", "1/6", "1/8", "1/4",
                "A", 8, 7040, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of the solid generated by rotating y = 1 - x^2 around the x-axis from x=0 to x=1.",
                "π/2", "π/3", "π/4", "2π/3",
                "A", 8, 7041, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = t^2 - 2t + 1. Find the displacement from t=0 to t=3.",
                "1", "0", "2", "3",
                "A", 8, 7042, "medium"));

        unit8Questions.add(new Question(
                "Find the centroid of the region under y = x^3 on [0,1].",
                "1/4", "3/4", "1/2", "1/3",
                "D", 8, 7043, "hard"));

        unit8Questions.add(new Question(
                "Compute the area under y = e^(-x) from x=0 to x=1.",
                "1 - 1/e", "1", "1/e", "e - 1",
                "A", 8, 7044, "medium"));

        unit8Questions.add(new Question(
                "Find the volume of the solid obtained by rotating y = sqrt(x) about the x-axis from x=0 to x=4.",
                "32π/3", "16π/3", "8π/3", "64π/3",
                "A", 8, 7045, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 5 - t^2. Find the total distance traveled from t=0 to t=2.",
                "8/3", "4/3", "2", "10/3",
                "A", 8, 7046, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = x + 1 about the x-axis from x=0 to x=1.",
                "7π/3", "5π/3", "6π/3", "4π/3",
                "A", 8, 7047, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = x^2 and y = 2x - x^2 on [0,1].",
                "1/2", "1/3", "1/4", "1/6",
                "B", 8, 7048, "medium"));

        unit8Questions.add(new Question(
                "Compute the average value of f(x) = sin(x) on [0, π].",
                "2/π", "1/π", "1/2", "0",
                "D", 8, 7049, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = t^2 + t. Find the displacement from t=0 to t=2.",
                "8/3", "4/3", "6/3", "10/3",
                "A", 8, 7050, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of the solid obtained by rotating y = x^2 + 2 around the x-axis from x=0 to x=1.",
                "14π/3", "16π/3", "12π/3", "10π/3",
                "A", 8, 7051, "medium"));

        unit8Questions.add(new Question(
                "Find the area under y = 1/(1 + x^2) from x=0 to x=1.",
                "π/4", "1/2", "1", "ln(2)",
                "A", 8, 7052, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of the solid generated by rotating y = x^3 from x=0 to x=1 about the x-axis.",
                "π/4", "π/5", "π/6", "π/3",
                "B", 8, 7053, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 2t + 1. Find the displacement from t=0 to t=3.",
                "9", "12", "6", "15",
                "A", 8, 7054, "easy"));

        unit8Questions.add(new Question(
                "Find the centroid of the region between y = x and y = 0 on [0,2].",
                "4/3", "2/3", "1", "3/2",
                "A", 8, 7055, "hard"));

        unit8Questions.add(new Question(
                "Compute the area between y = e^x and y = e^(-x) on [0,1].",
                "e - 1/e", "e + 1/e", "1 - 1/e", "1",
                "A", 8, 7056, "medium"));

        unit8Questions.add(new Question(
                "Find the volume of the solid obtained by rotating y = sqrt(1 - x^2) about the x-axis from x=0 to x=1.",
                "π/4", "π/2", "π/3", "π/6",
                "A", 8, 7057, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 3t - t^2. Find the total distance traveled from t=0 to t=3.",
                "9/2", "4", "3", "6",
                "A", 8, 7058, "medium"));

        unit8Questions.add(new Question(
                "Compute the area under y = cos(x) from x=0 to x=π/2.",
                "1", "0", "π/2", "1/2",
                "D", 8, 7059, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = x^3 and y = x^2 on [0,1].",
                "1/12", "1/6", "1/4", "1/8",
                "A", 8, 7060, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of the solid generated by rotating y = x^2 + x about the x-axis from x=0 to x=1.",
                "7π/6", "5π/6", "4π/6", "6π/6",
                "A", 8, 7061, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = t^2 - 4t + 3. Find the total distance traveled from t=0 to t=3.",
                "2", "3", "1", "0",
                "B", 8, 7062, "medium"));

        unit8Questions.add(new Question(
                "Compute the centroid of the region under y = x^2 on [0,2].",
                "8/3", "4/3", "2", "1",
                "B", 8, 7063, "hard"));

        unit8Questions.add(new Question(
                "Find the area under y = e^x from x=0 to x=1.",
                "e - 1", "1", "e", "e + 1",
                "A", 8, 7064, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of the solid obtained by rotating y = x + 2 around the x-axis from x=0 to x=1.",
                "13π/3", "10π/3", "12π/3", "11π/3",
                "A", 8, 7065, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = sin(x) and y = cos(x) on [0, π/4].",
                "√2/2 - 1/2", "1/2", "1/√2", "π/4",
                "A", 8, 7066, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 2t + 3. Find the displacement from t=0 to t=2.",
                "10", "8", "6", "12",
                "A", 8, 7067, "easy"));

        unit8Questions.add(new Question(
                "Compute the volume of the solid generated by rotating y = sqrt(x+1) from x=0 to x=3 about the x-axis.",
                "32π/3", "24π/3", "16π/3", "8π/3",
                "A", 8, 7068, "medium"));

        unit8Questions.add(new Question(
                "Find the area under y = 1/x from x=1 to x=2.",
                "ln(2)", "1", "2", "0",
                "A", 8, 7069, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = x^3 + 1 about the x-axis from x=0 to x=1.",
                "7π/4", "5π/4", "6π/4", "4π/4",
                "A", 8, 7070, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 3 - t^2. Find the total distance traveled from t=0 to t=2.",
                "10/3", "8/3", "4", "6",
                "B", 8, 7071, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = x^2 and y = x + 1 on [0,1].",
                "1/3", "1/2", "1/4", "1/6",
                "A", 8, 7072, "medium"));

        unit8Questions.add(new Question(
                "Compute the average value of f(x) = x^2 on [0,3].",
                "3", "2", "9/2", "1",
                "A", 8, 7073, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of the solid obtained by rotating y = e^x from x=0 to x=1 about the y-axis.",
                "π(e^2 - 1)/2", "π(e - 1)^2", "π(e^2 + 1)/2", "π(e - 1)",
                "A", 8, 7074, "hard"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 2t - 1. Find the displacement from t=0 to t=3.",
                "6", "4", "3", "5",
                "B", 8, 7075, "medium"));

        unit8Questions.add(new Question(
                "Find the centroid of the region under y = sqrt(x) on [0,4].",
                "8/3", "4/3", "2", "1",
                "A", 8, 7076, "hard"));

        unit8Questions.add(new Question(
                "Compute the area under y = cos(x) from x=0 to x=π/3.",
                "1/2", "1/4", "√3/2", "√3/4",
                "D", 8, 7077, "medium"));

        unit8Questions.add(new Question(
                "Find the volume of the solid obtained by rotating y = 1 - x^2 from x=0 to x=2 about the x-axis.",
                "8π/3", "16π/3", "4π/3", "2π/3",
                "B", 8, 7078, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = t^2 - 2t + 1. Find the total distance traveled from t=0 to t=3.",
                "2", "1", "0", "3",
                "A", 8, 7079, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = x^2 + 1 and y = x on [0,1].",
                "7/6", "5/6", "4/6", "6/6",
                "A", 8, 7080, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = x^2 + 2x about the x-axis from x=0 to x=1.",
                "11π/3", "10π/3", "12π/3", "9π/3",
                "A", 8, 7081, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 4t - t^2. Find the displacement from t=0 to t=3.",
                "9/2", "3", "6", "4",
                "A", 8, 7082, "medium"));

        unit8Questions.add(new Question(
                "Compute the centroid of the region under y = x^2 + x on [0,1].",
                "7/6", "2/3", "3/4", "1",
                "B", 8, 7083, "hard"));

        unit8Questions.add(new Question(
                "Find the area under y = e^x - 1 from x=0 to x=1.",
                "e - 2", "e - 1", "1", "e",
                "A", 8, 7084, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of the solid obtained by rotating y = x^3 + 1 about the x-axis from x=0 to x=1.",
                "5π/4", "4π/4", "6π/4", "7π/4",
                "A", 8, 7085, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = ln(x) and y = x - 1 on [1,2].",
                "ln(2) - 1/2", "ln(2) + 1/2", "1 - ln(2)", "1/2",
                "A", 8, 7086, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 3t - t^2. Find the displacement from t=0 to t=3.",
                "9/2", "3", "6", "4",
                "A", 8, 7087, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = sqrt(x) + 1 from x=0 to x=3 about the x-axis.",
                "20π/3", "16π/3", "18π/3", "22π/3",
                "A", 8, 7088, "medium"));

        unit8Questions.add(new Question(
                "Find the area under y = 1/(x^2 + 1) from x=0 to x=1.",
                "π/4", "1/2", "1", "0",
                "A", 8, 7089, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of the solid obtained by rotating y = x^2 about the y-axis from x=0 to x=1.",
                "π/2", "π/3", "π/4", "π/5",
                "A", 8, 7090, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 2t + 1. Find the total distance traveled from t=0 to t=2.",
                "6", "4", "5", "3",
                "A", 8, 7091, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = x and y = x^3 on [0,1].",
                "1/4", "1/3", "1/6", "1/2",
                "C", 8, 7092, "medium"));

        unit8Questions.add(new Question(
                "Compute the centroid of the region under y = sqrt(x) on [0,1].",
                "2/3", "1/2", "3/4", "1/3",
                "A", 8, 7093, "hard"));

        unit8Questions.add(new Question(
                "Find the area under y = sin(x) from x=0 to x=π/2.",
                "1", "0", "π/2", "1/2",
                "D", 8, 7094, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume of the solid obtained by rotating y = x^3 + x about the x-axis from x=0 to x=1.",
                "7π/4", "6π/4", "5π/4", "4π/4",
                "A", 8, 7095, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = 5 - t^2. Find the total distance traveled from t=0 to t=2.",
                "14/3", "16/3", "4", "6",
                "B", 8, 7096, "medium"));

        unit8Questions.add(new Question(
                "Find the area between y = e^x and y = 1 on [0,1].",
                "e - 2", "e - 1", "1", "2",
                "A", 8, 7097, "medium"));

        unit8Questions.add(new Question(
                "Compute the volume generated by rotating y = x^2 + 3 about the x-axis from x=0 to x=1.",
                "19π/3", "16π/3", "17π/3", "18π/3",
                "A", 8, 7098, "medium"));

        unit8Questions.add(new Question(
                "A particle moves along a line with velocity v(t) = t^2 - t. Find the displacement from t=0 to t=3.",
                "3", "4", "2", "1",
                "A", 8, 7099, "medium"));


        numUnit8Questions = unit8Questions.size();
        System.out.printf("There are %d questions in unit 8%n", numUnit8Questions);

    }

}
